"""add user profiles and tech stack tables

Revision ID: f1f09e344b04
Revises: ed032ff43dd7
Create Date: 2026-03-02 03:12:18.139830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1f09e344b04'
down_revision: Union[str, Sequence[str], None] = 'ed032ff43dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_items_category'), 'tech_items', ['category'], unique=False)
    op.create_index(op.f('ix_tech_items_id'), 'tech_items', ['id'], unique=False)
    op.create_index(op.f('ix_tech_items_slug'), 'tech_items', ['slug'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('user_stack_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tech_id'], ['tech_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tech_id', name='uq_user_tech')
    )
    op.create_index(op.f('ix_user_stack_items_id'), 'user_stack_items', ['id'], unique=False)
    op.create_index(op.f('ix_user_stack_items_tech_id'), 'user_stack_items', ['tech_id'], unique=False)
    op.create_index(op.f('ix_user_stack_items_user_id'), 'user_stack_items', ['user_id'], unique=False)
    op.create_index('ix_user_stack_user_tech', 'user_stack_items', ['user_id', 'tech_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_stack_user_tech', table_name='user_stack_items')
    op.drop_index(op.f('ix_user_stack_items_user_id'), table_name='user_stack_items')
    op.drop_index(op.f('ix_user_stack_items_tech_id'), table_name='user_stack_items')
    op.drop_index(op.f('ix_user_stack_items_id'), table_name='user_stack_items')
    op.drop_table('user_stack_items')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_tech_items_slug'), table_name='tech_items')
    op.drop_index(op.f('ix_tech_items_id'), table_name='tech_items')
    op.drop_index(op.f('ix_tech_items_category'), table_name='tech_items')
    op.drop_table('tech_items')
    # ### end Alembic commands ###
